spring.datasource.url=jdbc:postgresql://localhost:5432/shift_db
spring.datasource.username=postgres
spring.datasource.password=Sasuke4575
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect